### ISSUE TITLE
Package install fails - unable to connect to github.com

### ISSUE THREAD

**Issue by duckboy1981** [atom-ide-community/atom-script#1058]
When I try to install the Script package through Atom I receive the following error -

> Installing “script@3.9.0” failed.

I've tried downloading and installing manually, but the package fails to activate due to a missing dependency (Underscore).  Presumably, under normal circumstances downloading the package via Atom should take care of all dependencies (correct me if I'm wrong).

I'm using Windows 8 with Atom version 1.9.9, and Script version 3.9.0.

Here is the full error output from the failed install via Atom -

```
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\dgard\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\dgard\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\dgard\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.253.113]: errno=Invalid argument
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\dgard\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dgard\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\dgard\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\dgard\\.atom\\.apmrc" "install" "C:\\Users\\dgard\\AppData\\Local\\Temp\\d-116726-6428-b04ygd\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Invalid argument
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

And here is the output produced in a command prompt when I try to install the package manually.  Note that doing this to other packages produces the result **done** -

```
c:\Users\dgard\.atom\packages\atom-script>apm install
Installing modules failed
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm WARN prefer global coffee-script@1.10.0 should be installed with -g
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! git clone --template=C:\Users\dgard\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\dgard\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\dgard\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.253.113]: errno=Invalid argument
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\dgard\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dgard\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\dgard\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\dgard\\.atom\\.apmrc" "install" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\dgard\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=Invalid argument
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by fasiha** [comment]
Worked fine for me just now.

**Comment by GianpieroCea** [comment]
I have a similar issue(but I am not sure if it's the same problem,**can somebody check if it's a different issue**?) . Basically when I try to install Script through Atom I have got the same error @duckboy1981 had despite having a working Git .
The error I get when trying to install with apm from command line is the following:

`C:\Users\pc>apm install script
Installing script to C:\Users\pc\.atom\packages failed

npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\pc\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone C:\Users\pc\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\pc\AppData\Local\Temp\npm-13352-3b2ad20b\git-cache-ae64e6663831\5ff35d61ff600391ccd784a18616fa73c09e0aea: Cloning into 'C:\Users\pc\AppData\Local\Temp\npm-13352-3b2ad20b\git-cache-ae64e6663831\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! git clone C:\Users\pc\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\pc\AppData\Local\Temp\npm-13352-3b2ad20b\git-cache-ae64e6663831\5ff35d61ff600391ccd784a18616fa73c09e0aea: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\pc\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\pc\AppData\Local\Temp\npm-13352-3b2ad20b\git-cache-ae64e6663831\5ff35d61ff600391ccd784a18616fa73c09e0aea: fatal: unable to fork
npm ERR! git clone C:\Users\pc\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 C:\Users\pc\AppData\Local\Temp\npm-13352-3b2ad20b\git-cache-ae64e6663831\5ff35d61ff600391ccd784a18616fa73c09e0aea:
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\pc\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\pc\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\pc\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\pc\\.atom\\.apmrc" "install" "C:\\Users\\pc\\AppData\\Local\\Temp\\d-116726-14404-148kq21\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\pc\AppData\Local\Temp\npm-13352-3b2ad20b\git-cache-ae64e6663831\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>`

Any comment would be much appreciated.

**Comment by GianpieroCea** [comment]
I managed to make it work!  I used #1039  . Great solution.
