### ISSUE TITLE
Downloading takes forever

### ISSUE THREAD

**Issue by deuel18** [atom-ide-community/atom-script#1196]
I'm not sure if its the nature of it but the downloading session seems to take very long time. I've been downloading the package multiple times with each download interval of about 4 to 5 hours but nothing seems to be working. Its showing the install animation but that's it. I dont know if I'm the only one experiencing such problem.

**Comment by chahatupreti** [comment]
I have the same problem. I tried to download 'script' package in Atom, and it is taking forever to download. I don't even know how large the package is, so that I may be able to understand if its slow because of the size. Screenshot uploaded.
![atom](https://cloud.githubusercontent.com/assets/9638057/26058846/40edbee4-399d-11e7-829c-31800bda4c87.png)
