### ISSUE TITLE
'python' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by hulkbuddha** [atom-ide-community/atom-script#1536]
What could be the problem ?

**Comment by jparet** [comment]
Stupid suggestions for Windows users but:
- Is your Python correctly installed ?
https://wiki.python.org/moin/BeginnersGuide/Download
- Is the path to your Python is in your Window PATH ?
https://www.computerhope.com/issues/ch000549.htm

**Comment by guyman575** [comment]
I have this same issue. The reason seems to be that the default command in windows to launch python is 'py' and not 'python'. Is there a way to change what command is used for a given language?

**Comment by jparet** [comment]
No, the default command on Windows is 'python'.

Try to find your python directory (has to be included into your Windows PATH) and check if you have python.exe or py.exe. If you have py.exe then rename it to python.exe.

You can also try to simply reinstall python on your device, from the correct source.

**Comment by guyman575** [comment]
Reinstalling python is how I got it to be py. I think it has changed and now on windows that seems to be the default. I just did a fresh installation of python on windows and that is what it gives you. I know how to change it, but it would be nice to have a feature that allows it to be changed similar to the atom-runner package

**Comment by jparet** [comment]
OK, I didn't know this recent change if confirmed.
In the other hand, it sounds strange that you can not run python with the 'old' command even if the program is named python.exe and you have the directory path of this python.exe into your Windows path.
Anyway, atom-script has a configure script option that lets you the power to create then run atom-script with different profiles where you can specify the command to run and other stuffs. Really usefull when you use it to fastly run the default main script of a package, or to run the test part, or to use a different python version...

**Comment by guyman575** [comment]
This is what I was looking for, but currently when I type ctrl+shift+p and type 'script: ' there is no option for configure script. Is there some way to enable it? Sorry If I am missing something

**Comment by guyman575** [comment]
Managed to resolve it by modifying the python installation, thank you for your help :)

**Comment by jparet** [comment]
Hey, you are rigth: ctrl + shift + p then typing 'script' leads to some options of the 'Script' package but not to all of them.

The current way I take is clicking to the 'Packages' menu on the top of the atom editor and then clicking on the 'Script' package to display all the options. Here you get the 'Configure Script' and others like 'Run with Profile'.

And in my 'File > Keymap...' cson file:

``` cson
'atom-text-editor':
  # better keyboard shortcuts for the 'script' package
  'ctrl-numpad1': 'script:run'
  'ctrl-numpad2': 'script:run-with-profile'
  'ctrl-numpad3': 'script:run-options'
```

**Comment by shreyamadaan2503** [comment]
Follow these steps:
ctrl+shift+P
Search for script and select Script: run options
Specify the path where python is installed in environment variables here
save it as a profile
Should work fine now

**Comment by AniobiStanley** [comment]
After specifying my python command path: "C:\Users\...\AppData\Local\Programs\Python\Python36-32" I still get this error message: "The system cannot find the path specified."

**Comment by amitsoftdeveloper** [comment]
where shoud we do the ctrl+shift+p maam

**Comment by amitsoftdeveloper** [comment]
C:\Python\python.exe C:/Users/amit/PycharmProjects/indianworld/desktopAssistant.py
I am ready for your command
'say' is not recognized as an internal or external command,
operable program or batch file.
Ready...
Your last command couldn't be heard
Ready...
Your last command couldn't be heard
Ready...

Process finished with exit code -1

**Comment by amitsoftdeveloper** [comment]
A. The system path is a list of folders, separated by a semicolon, that identifies the folders that the system should search when looking for files that are called from the Run dialog box, command line, or other processes. Normal program installation changes this path to include the program's installation path.

See also, "How do I add a folder to the Windows 2000/Windows XP PATH, in a batch?" and "Securing the Windows Search Path."

To change the system path, perform these steps:

 Start the System Control Panel applet (Start - Settings - Control Panel - System).
 Select the Advanced tab.
 Click the Environment Variables button.
 Under System Variables, select Path, then click Edit.
 You'll see a list of folders, as this example for my system shows: C:\Program Files\Windows Resource Kits\Tools\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;C:\Program Files\Support Tools\;C:\Program Files\Common Files\Roxio Shared\DLLShared;C:\Program Files\Common Files\Ulead Systems\MPEG;C:\Program Files\Intel\DMIX;C:\Program Files\Executive Software\Diskeeper\;C:\Program Files\Bonjour\;C:\Program Files\QuickTime\QTSystem\;C:\Program Files\Misc
 You can add additional folders that you want to include in searches. I add a "C:\program files\misc" entry into which I place my standalone utilities, instead of copying them into C:\windows. Click OK.
 You'll need to restart the processes (e.g., command prompt) that use the system path to see the added folders.
An alternative to setting the path at system level is to change it at user level; however, doing so will affect only your logon session and not other users who might use the computer or system processes, which might cause confusion and unexpected behavior. You can also set the path at a system level by using the setx command with the -m switch.
