### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by rgbkrk** [atom-ide-community/atom-script#1550]
Hey all!

If you're seeing this you're either:

* Already a maintainer
* Perusing issues as a friendly person

I'd really like to have someone take the mantle on this package as I cannot lead it whatsoever with my current obligations. I've added a _lot_ of maintainers, no one to fully take it on though.

Here's what I'm looking for:

0. Become a maintainer by submitting fixes to the current code base
1. Make a release of the package, announcing it as an issue
2. Make another release, announcing it again
3. I'm transferring the package to you
4. 🎉 

🙇 Thanks for your help

**Comment by Jereeee** [comment]
Hello there, I'm not a maintainer but I just wanted to tell you that you can fix a small bug while running python code. Just change "python" to "py". It was changed to be like that

**Comment by akaashhazarika** [comment]
I would like to be a maintainer of this code.

**Comment by rgbkrk** [comment]
Great, in order to complete step 0 you'll need to make a PR and get it merged. Let me know when ready.

**Comment by vergenzt** [comment]
@rgbkrk great foundation for a package! I have some improvements I'm interested in making soon and may be open to taking the package over if I find I have bandwidth.

In no particular order:

1) Switch to using Atom's [config API](https://flight-manual.atom.io/api/v1.7.2/Config/#config-schemas) to persist saved profiles instead of the [serialization API](https://flight-manual.atom.io/behind-atom/sections/serialization-in-atom/), so profile edits are free. (#787)

2) Maybe clean up some of the backlog of issues? Or least close duplicates. 1,027 total at time of writing. (Maybe also get rid of [`createGitHubIssueLink`](https://github.com/rgbkrk/atom-script/blob/9d5f0e22e95efd4f98de1afb47138e5dc784ccdf/lib/script-view.js#L107-L124)?  😬)

3) Longer term, I'd love to maybe improve the environment variables profile section by:
  - a) letting it be a key/value table (e.g. see Postman query params interface) rather than a single `KEY1=value1; KEY2=value2` text box, and
  - b) _maybe_... have a "Secret" checkbox next to each key that
     - (i) switches the value to a hidden password-style field, and
     - (ii) persists the value in the OS keychain using [node-keytar](https://github.com/atom/node-keytar). 🤔 

Thoughts?

**Comment by rgbkrk** [comment]
I have like zero time for this project and am fully on VS Code now, so I'm just plain happy to have others on top of this stuff. I'll take a look at your PR @vergenzt and add you on as a maintainer.

**Comment by rgbkrk** [comment]
Ah, that PR you linked wasn't yours. Please make a PR for any of the areas you're mentioning and we'll have you maintain after that.

**Comment by AlexThundrous** [comment]
Please add input support for script

**Comment by kadirselcuk** [comment]
Herkese Merhaba atom sözdizimi bakımcılarına çağrı yapıyorum

**Comment by aminya** [comment]
@rgbkrk We are interested to maintain this repository. I am the owner of @atom-ide-community. I have sent you an invitation. If you can transfer the repository there, we will maintain it.

**Comment by rgbkrk** [comment]
May want to try the invitation again, I don't see it when I visit https://github.com/atom-ide-community or https://github.com/orgs/atom-ide-community/people, nor do I have an email.

**Comment by aminya** [comment]
Sorry, I didn't get a notification for your response. I have sent the invitation again. Please let me know if you have received it. @rgbkrk

**Comment by rgbkrk** [comment]
Sadly I viewed this 8 days after. 🙄  Apologies. Send again, I'm "back" from the holidays.

**Comment by aminya** [comment]
@rgbkrk I sent you a new invitation. Happy holidays! 😄

**Comment by rgbkrk** [comment]
Closed, good luck @atom-ide-community/atom-community

**Comment by aminya** [comment]
@rgbkrk Thank you 🎉
