### ISSUE TITLE
Installing “script@3.6.3” failed.

### ISSUE THREAD

**Issue by kraang** [atom-ide-community/atom-script#881]
Installing “script@3.6.3” failed.

npm ERR! Command failed: Cloning into 'C:\Users\UIGIYU~1\AppData\Local\Temp\npm-18780-ed7f828c\git-cache-0c3c81978cc8\5ff35d61ff600391ccd784a18616fa73c09e0aea'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by DemersM** [comment]
Intalling failed also for me

npm ERR! Command failed: Cloning into bare repository 'C:\Users\DemMa18\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.122]: errno=Invalid argument
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

I am on Windows

**Comment by hyst329** [comment]
This may be related to the Git version (more precisely, the Git distro, see below) you're using. If you're on Windows, **use Git for Windows** (and not, for example, the MSYS2's one). I've also experienced such errors, and removing MSYS2 dirs from PATH helped me. Note that doesn't seem to depend on the Git version itself (on my machine both Git programs are 2.7.0)

**Comment by DemersM** [comment]
I have Git 2.7.0 too and MSYS32 is not in my PATH
I tryed to install this package manuelly with apm after cloning the repo to a local directory (see: https://github.com/rgbkrk/atom-script#i-already-cloned-it) but I have the same error

**Comment by DemersM** [comment]
The problem was the installation of node-simple-plist. This library is deprecated in favor to lodash. Why is it still in atom-script dependancy list?

**Comment by hyst329** [comment]
@DemersM My problem was also related to this dependency. Could you show your `npm` log, please?

**Comment by DemersM** [comment]
the repo monsterkodi/node-simple-plist does not exists anymore. That's why git return connection error. This library is not a dependancy of atom-script, it's not listed in package.json. It's a dependancy of a dependancy... I dont know which one, maybe coffeeScript

**Comment by DemersM** [comment]
$ apm install
Installing modules failed
npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/monsterkodi/node-simple-plist.git resetting remote C:\Users\DemMa18\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\DemMa18\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\DemMa18\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: Cloning into bare repository 'C:\Users\DemMa18\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! git clone --template=C:\Users\DemMa18\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\DemMa18\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\DemMa18\.atom\.apm\_git-remotes\_templates --mirror git://github.com/monsterkodi/node-simple-plist.git C:\Users\DemMa18\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541: github.com[0: 192.30.252.129]: errno=Invalid argument
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\DemMa18\\AppData\\Local\\atom\\app-1.7.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\DemMa18\\AppData\\Local\\atom\\app-1.7.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\DemMa18\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\DemMa18\\.atom\\.apmrc" "install" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\DemMa18\.atom\.apm\_git-remotes\git-github-com-monsterkodi-node-simple-plist-git-6a71a541'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Invalid argument
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by DemersM** [comment]
this line: git clone --template=C:\Users\DemMa18.atom.apm_git-remotes_templates --mirror git://github.com/monsterkodi/node-simple-plist.git 

it tryes to clone using git://github.com/monsterkodi/node-simple-plist.git  instead it should use http://github.com/monsterkodi/node-simple-plist.git

**Comment by hyst329** [comment]
@DemersM if it's related to #820, check your firewall connection. I also recommend you to execute`where git` in the command line to assure that you're using the proper Git executable.

**Comment by DemersM** [comment]
I cant change my firewall settings and using `git config --global url."https://".insteadOf git://` did not solve the problem

**Comment by DemersM** [comment]
Is there a way to install `node-simple-plist` manually? Where should I put this library folder to prevent `Script `installation to try clone it?
