### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by gowerc** [atom-ide-community/atom-script#960]
Hey,

I am trying to install from the package manager inside of atom and am getting the following error message

```
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
```

Full error message attached. 
[Error.txt](https://github.com/rgbkrk/atom-script/files/300327/Error.txt)

**Comment by dyphoenix** [comment]
I met this matter...
-----------------------------------------------------
installing “script@3.7.3” failed.

Failed to install script because Git was not found.

The script package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

**Comment by gowerc** [comment]
Hi,

Thanks for your reply.

I did already have GIT installed on my machine. Here are the results of the apm -v command

apm  1.9.2
npm  2.13.3
node 0.10.40
python
git 1.9.5.msysgit.0
visual studio

**Comment by Noedel-Man** [comment]
same here error git not found. git 2.8.1.windows.1
